### ISSUE TITLE
After installation, running test produces sqlite error

### ISSUE THREAD

**Issue by dreamingmind** [pakacuda/cakephp-fixture-factories#8]
I've followed the install instructions successfully. Composer ran fine, plugin loaded in Application.php, listener added to phpunit.xml. I did not however do the steps related to migrations as this appears optional. Cake version 4.0.7

After installation I am able to bake the factories without error.

Running tests produces:

```
Dons-MacBook-Pro:ampfg4 dondrake$ vendor/bin/phpunit
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.

Exception: SQLSTATE[HY000]: General error: 1 no such table: sqlite_sequence
In [/Library/WebServer/Documents/ampfg4/vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php, line 120]

```
I'm using a mysql db, not sqlite.

If I remove the listener from the xml I can successfully run my tests. I can even make very limited use of the factories but truncation seems to be out of commission. Perhaps that is what the listeners are managing?

If I add the line regarding migrations to the bootstrap, the result is the same.

I did debug the value returned by the FixtureManager::getConnection() and it seems to be returning my expected mysql configuration settings.

**Comment by pabloelcolombiano** [comment]
Hi,

how does your test table configuration file looks likes?
It seems as if you did not configure your test DB to mysql, but Sqlite.

**Comment by dreamingmind** [comment]
This is my configurations array for the tables

```
    'Datasources' => [
        'default' => [
            'host' => 'mysql.myhost.com',
            'username' => 'myuser_web',
            'password' => 'secret',
//            'database' => 'ampfg4_dev',
            'database' => 'ampfg4_prod',
        ],
        'test' => [
            'datasource' => 'Cake\Database\Driver\Mysql',
            'host' => 'mysql.myhost.com',
            'username' => 'myuser_web',
            'password' => 'secret',
            'database' => 'ampfg4_test',
        ],
    ],
```

If I remove the listener from the xml my tests run on the expected database.

I added the explicit 'datasource' declaration as part of my effort to get this running. 

I traced the flow of code to the point of the error and put a debug in FixtureManager::getConnection() to see what it was getting. It appears to have successfully loaded my configuration.

I thought it might be a PHPStorm configuration problem since I am running my test in the IDE. But when I run them directly from the terminal I get the same error.

My schema does not include a file called `sqlite_sequence` or anything followed by the word sequence.

**Comment by dreamingmind** [comment]
There is some struggle to get make the connection though. I just don't understand it or its relationship to the listener inclusion.

Getting the stack trace from to point off error like this:

<img width="1000" alt="Screen Shot 2020-05-17 at 8 04 23 AM" src="https://user-images.githubusercontent.com/1307216/82152313-1870c400-9815-11ea-993d-d1cb51cd096a.png">

Gets this:

```
Cake\\Database\\Driver\\Sqlite::prepare() - CORE/src/Database/Driver/Sqlite.php, line 121
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 283
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::prepare() - CORE/src/Database/Connection.php, line 290
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 357
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::query() - CORE/src/Database/Connection.php, line 361
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 310
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::execute() - CORE/src/Database/Connection.php, line 314
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::truncate() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 14
CakephpFixtureFactories\\TestSuite\\FixtureManager::truncateDirtyTablesForAllTestConnections() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureManager.php, line 50
CakephpFixtureFactories\\TestSuite\\FixtureInjector::startTest() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureInjector.php, line 45
PHPUnit\\Framework\\TestResult::startTest() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 411
PHPUnit\\Framework\\TestResult::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 628
PHPUnit\\Framework\\TestCase::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestCase.php, line 763
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\TextUI\\TestRunner::doRun() - ROOT/vendor/phpunit/phpunit/src/TextUI/TestRunner.php, line 621
PHPUnit\\TextUI\\Command::run() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 204
PHPUnit\\TextUI\\Command::main() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 163
[main] - ROOT/vendor/phpunit/phpunit/phpunit, line 61''Cake\\Database\\Driver\\Sqlite::prepare() - CORE/src/Database/Driver/Sqlite.php, line 121
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 283
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::prepare() - CORE/src/Database/Connection.php, line 290
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 357
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::query() - CORE/src/Database/Connection.php, line 361
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 310
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::execute() - CORE/src/Database/Connection.php, line 314
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::CakephpFixtureFactories\\TestSuite\\Truncator\\{closure}() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 20
Cake\\Database\\Connection::transactional() - CORE/src/Database/Connection.php, line 692
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::truncate() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 33
CakephpFixtureFactories\\TestSuite\\FixtureManager::truncateDirtyTablesForAllTestConnections() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureManager.php, line 50
CakephpFixtureFactories\\TestSuite\\FixtureInjector::startTest() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureInjector.php, line 45
PHPUnit\\Framework\\TestResult::startTest() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 411
PHPUnit\\Framework\\TestResult::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 628
PHPUnit\\Framework\\TestCase::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestCase.php, line 763
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\TextUI\\TestRunner::doRun() - ROOT/vendor/phpunit/phpunit/src/TextUI/TestRunner.php, line 621
PHPUnit\\TextUI\\Command::run() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 204
PHPUnit\\TextUI\\Command::main() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 163
[main] - ROOT/vendor/phpunit/phpunit/phpunit, line 61''Cake\\Database\\Driver\\Sqlite::prepare() - CORE/src/Database/Driver/Sqlite.php, line 121
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 283
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::prepare() - CORE/src/Database/Connection.php, line 290
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 340
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::run() - CORE/src/Database/Connection.php, line 345
Cake\\Database\\Query::execute() - CORE/src/Database/Query.php, line 245
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::CakephpFixtureFactories\\TestSuite\\Truncator\\{closure}() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 25
Cake\\Database\\Connection::transactional() - CORE/src/Database/Connection.php, line 692
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::truncate() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 33
CakephpFixtureFactories\\TestSuite\\FixtureManager::truncateDirtyTablesForAllTestConnections() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureManager.php, line 50
CakephpFixtureFactories\\TestSuite\\FixtureInjector::startTest() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureInjector.php, line 45
PHPUnit\\Framework\\TestResult::startTest() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 411
PHPUnit\\Framework\\TestResult::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 628
PHPUnit\\Framework\\TestCase::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestCase.php, line 763
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\TextUI\\TestRunner::doRun() - ROOT/vendor/phpunit/phpunit/src/TextUI/TestRunner.php, line 621
PHPUnit\\TextUI\\Command::run() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 204
PHPUnit\\TextUI\\Command::main() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 163
[main] - ROOT/vendor/phpunit/phpunit/phpunit, line 61''Cake\\Database\\Driver\\Sqlite::prepare() - CORE/src/Database/Driver/Sqlite.php, line 121
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 283
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::prepare() - CORE/src/Database/Connection.php, line 290
Cake\\Database\\Connection::Cake\\Database\\{closure}() - CORE/src/Database/Connection.php, line 340
Cake\\Core\\Retry\\CommandRetry::run() - CORE/src/Core/Retry/CommandRetry.php, line 69
Cake\\Database\\Connection::run() - CORE/src/Database/Connection.php, line 345
Cake\\Database\\Query::execute() - CORE/src/Database/Query.php, line 245
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::CakephpFixtureFactories\\TestSuite\\Truncator\\{closure}() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 30
Cake\\Database\\Connection::transactional() - CORE/src/Database/Connection.php, line 692
CakephpFixtureFactories\\TestSuite\\Truncator\\SqliteTruncator::truncate() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/Truncator/SqliteTruncator.php, line 33
CakephpFixtureFactories\\TestSuite\\FixtureManager::truncateDirtyTablesForAllTestConnections() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureManager.php, line 50
CakephpFixtureFactories\\TestSuite\\FixtureInjector::startTest() - ROOT/vendor/pakacuda/cakephp-fixture-factories/src/TestSuite/FixtureInjector.php, line 45
PHPUnit\\Framework\\TestResult::startTest() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 411
PHPUnit\\Framework\\TestResult::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestResult.php, line 628
PHPUnit\\Framework\\TestCase::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestCase.php, line 763
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\Framework\\TestSuite::run() - ROOT/vendor/phpunit/phpunit/src/Framework/TestSuite.php, line 597
PHPUnit\\TextUI\\TestRunner::doRun() - ROOT/vendor/phpunit/phpunit/src/TextUI/TestRunner.php, line 621
PHPUnit\\TextUI\\Command::run() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 204
PHPUnit\\TextUI\\Command::main() - ROOT/vendor/phpunit/phpunit/src/TextUI/Command.php, line 163
[main] - ROOT/vendor/phpunit/phpunit/phpunit, line 61'Exception: SQLSTATE[HY000]: General error: 1 no such table: sqlite_sequence
In [/Library/WebServer/Documents/ampfg4/vendor/cakephp/cakephp/src/Database/Driver/Sqlite.php, line 122]
```

**Comment by pabloelcolombiano** [comment]
I cannot explain right now, being on my bike with no computers around, why Sqlite is detected as the test DB driver. I'll have to dig into it in a week. Using MySql, which is your case, should never produce an issue with Sqlite intern related tables. There is nothing wrongly done there on your side.

What happens if you add

'driver' => Mysql::class,

 to the test configuration in your app.php file?

**Comment by pabloelcolombiano** [comment]
I cannot explain right now, being on my bike with no computers around, why Sqlite is detected as the test DB driver. I'll have to dig into it in a week. Using MySql, which is your case, should never produce an issue with Sqlite intern related tables. There is nothing wrongly done there on your side.

What happens if you add

`'driver' => `Mysql::class,`

 to the test configuration in your app.php file?

For the moment, only
`\Cake\Database\Driver\Mysql::class`
and 
`\Cake\Database\Driver\Sqlite::class`
are natively being supported by the package. Your case should therefore be covered, if you specify the first one.

**Comment by dreamingmind** [comment]
I get the same result with that alternative 'driver' setting.

The good news is, if I suppress the listener reference and manually set each test's `fixtures` property, the post-test cleanup gets done properly and I can use the fixture factories.

<img width="801" alt="Screen Shot 2020-05-17 at 7 09 27 PM" src="https://user-images.githubusercontent.com/1307216/82167871-f78a8c00-9871-11ea-874a-04cedb632e85.png">

**Comment by dreamingmind** [comment]
I had one thought about a possible cause. It didn't turn out to be the problem but I'm noting it a s negative evidence.

The cake fixtures seem to drop the tables when the test is done, so I imagined that as FixtureFactory tried to connect for a test on a table that did not exist it would start through a series of attempts with different connections.

But, insuring all the tables exist and removing the standard fixture listener so the tables did not get dropped did not solve the problem.

**Comment by dreamingmind** [comment]
I've also made an effort to understand what is going on to see if I have something wrong on my end. But I'm not really catching on. The whole thing is pretty opaque to me.

Non the less, here are the queries that are getting passed to the failing line 120 and short stack traces of the callers.

If my experiments and comments are useless noise let me know and I'll stop :-)

```
Cake\Database\Connection Line:307
Cake\Database\Connection Line:361
Cake\Database\Connection line 284

 SELECT table_name, table_rows
 FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA = 'ampfg4_test' and AUTO_INCREMENT > 1;
```

```
Cake\Database\Connection Line:307
Cake\Database\Connection Line:361
Cake\Database\Connection line 284

 SELECT name FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence' AND name NOT LIKE '%phinxlog';

```
```
Cake\Database\Connection Line:307
Cake\Database\Connection Line:361
Cake\Database\Connection line 284

 pragma foreign_keys = off;
```

```
Cake\Database\Connection Line:343
Cake\Database\Connection line 284

 DELETE FROM requests
```

```
Cake\Database\Connection Line:343
Cake\Database\Connection line 284

 DELETE FROM sqlite_sequence WHERE name = :c0
```

**Comment by pabloelcolombiano** [comment]
@dreamingmind Thanks for trying. Noise is good.

1. I do not see any reference in the [docs](`https://book.cakephp.org/4/en/orm/database-basics.html#configuration) to a `datasource` key in the DB configs. I would therefore get rid of it, and set the `driver` properly - which you apparently already did.

If this still does not work:

2. We have in the meanwhile slightly modified the code, so please update our package to a newer version (v0.2.10). This might handle your issue.

If possible, please have a try on
a) a test class without CakePHP fixtures
b) as well as on a test class using both CakePHP fixtures and Fixture Factories

I am looking forward to your feedback!

**Comment by dreamingmind** [comment]
Alright! I found the cause of the problem. Something in my setup is letting the DebugKit connections go through the cleanup process and that is triggering the failure.

In `CakephpFixtureFactories\TestSuite\FixtureManager` this is the actual test that is allowing debug kit to participate:

<img width="909" alt="Screen Shot 2020-05-31 at 9 17 11 AM" src="https://user-images.githubusercontent.com/1307216/83357229-f3ee0f00-a31f-11ea-9164-9ca8081b14dc.png">

this is the var_export result:

<img width="852" alt="Screen Shot 2020-05-31 at 9 18 03 AM" src="https://user-images.githubusercontent.com/1307216/83357248-14b66480-a320-11ea-940f-742b748d1c56.png">

**Comment by pabloelcolombiano** [comment]
O.K. let me know if you managed to solve that issue is 100% on your side, or if you think the package should be adjusted to avoid that kind of trouble.

**Comment by dreamingmind** [comment]
Well, let me shift focus for minute. 

When I suppress the conditional so everything operates as expected I see a large slow-down on the execution of my tests. 

This seems to be because many of my tests don't actually use fixtures but the fixture_factory cleanup seems to run on every test anyway.

Is it possible that the clean-up process is simply too permissive; running everything, all the time?

If so, the problem I'm seeing is a side effect that would go away if the clean-up only ran on connections and tables that had actually been used in a test.

I'm assuming the Cake-native fixture process does something like this. Possibly they are using the `$fixtures` property to limit clean-up activity. FixtureFactory does not require this property (an advantage) but that means you had to find another way to decide what to clean up.

Would it be possible for the factories to record their use during each test so when the test ends that record could be used to precisely clean up only the tables that needed it?

**Comment by pabloelcolombiano** [comment]
1. Indeed the native CakePHP fixtures truncates only the "dirty tables", namely those that have been loaded in the test classes

2. This is also what the fixture factories do, but by diretly querying the DB. For Mysql for example, the query is located in the `MysqlTableSniffer.php` file (https://github.com/pakacuda/cakephp-fixture-factories/blob/master/src/TestSuite/Sniffer/MysqlTableSniffer.php). Only the "dirty tables" are being truncated between each tests.

Are you using both CakePHP native Fixtures and the fixture factories? This would make the truncation redundant. How is the performance observed on a test class that does not load any CakePHP native fixtures?

**Comment by dreamingmind** [comment]
Hmm... Okay. I'll dig deeper to understand what I'm seeing. 

I have a test class with no fixture involvement, 38 tests and over 100 assertions. Without the Factory listener it runs in less than a second. With the listener it runs at over 1 minute.

With the listener suppressed:

<img width="851" alt="Screen Shot 2020-05-31 at 5 58 42 PM" src="https://user-images.githubusercontent.com/1307216/83367296-b2358680-a368-11ea-8321-e64b46a74e45.png">

With the listener listening:

<img width="830" alt="Screen Shot 2020-05-31 at 5 58 23 PM" src="https://user-images.githubusercontent.com/1307216/83367300-b661a400-a368-11ea-9a67-ce487c8322c5.png">

**Comment by pabloelcolombiano** [comment]
I have run a couple of performance tests on Sqlite where I create 10 entities in three different scenarios, with the whole suite being run 1000 times:
A. With the legacy CakePHP fixtures and listeners (8 fixtures): 3.12 minutes
B. With the CakePHP fixture factories and listeners: 2.96 minutes
C. Same as 2., but with the loading of 8 CakePHP fixtures: 3.47 minutes.

A. and B. are comparable. C. is as expected over 10% slower. If you load more fixtures, it will get even slower.

I obtain similar results with MySQL.

**Comment by pabloelcolombiano** [comment]
@dreamingmind I can reproduce your issue: you now have two listeners. You should replace the CakePHP native listener by the package's listener. This should bring your test to the original speed.

The documentation is not very clear on that point, I'll amend that.

**Comment by dreamingmind** [comment]
Thanks! Commit  #fef53e2 resolved my sqlite issue. 

I'll get my code put back together and carry on. Any of the other areas of discussion in this thread I will research and take up in a new issue if necessary.

**Comment by pabloelcolombiano** [comment]
Thank you for the feedback. I am glad things are working again on your side.

Did the speed issue get solved by replacing the CakePHP listener and injector by the ones of the package in your `phpunit.xml` file, instead of adding them?

**Comment by dreamingmind** [comment]
I still have a speed issue. But I want to work out what is really going on. Once I've sure it's not something I'm doing I'll let you know. It appears in tests that make no use of the db at all.

Also I'm having a problem with a foreign_key constraint that's throwing an error at the end of the tests. But again, I want to be sure it's not some problem in my own code.
